# Generated by Django 3.0.5 on 2020-05-03 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200503_1149'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='tags',
            new_name='ags',
        ),
    ]
